# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ttchef/coding/c/tanks

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ttchef/coding/c/tanks

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ttchef/coding/c/tanks/CMakeFiles /home/ttchef/coding/c/tanks//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ttchef/coding/c/tanks/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ttchef/coding/c/tanks/CMakeFiles /home/ttchef/coding/c/tanks//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ttchef/coding/c/tanks/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arc

# Build rule for target.
arc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arc
.PHONY : arc

# fast build rule for target.
arc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arc.dir/build.make CMakeFiles/arc.dir/build
.PHONY : arc/fast

#=============================================================================
# Target rules for targets named shaders

# Build rule for target.
shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shaders
.PHONY : shaders

# fast build rule for target.
shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/build
.PHONY : shaders/fast

#=============================================================================
# Target rules for targets named sausages

# Build rule for target.
sausages: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sausages
.PHONY : sausages

# fast build rule for target.
sausages/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/build
.PHONY : sausages/fast

core.o: core.c.o
.PHONY : core.o

# target to build an object file
core.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/core.c.o
.PHONY : core.c.o

core.i: core.c.i
.PHONY : core.i

# target to preprocess a source file
core.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/core.c.i
.PHONY : core.c.i

core.s: core.c.s
.PHONY : core.s

# target to generate assembly for a file
core.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/core.c.s
.PHONY : core.c.s

core_archive.o: core_archive.c.o
.PHONY : core_archive.o

# target to build an object file
core_archive.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arc.dir/build.make CMakeFiles/arc.dir/core_archive.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/core_archive.c.o
.PHONY : core_archive.c.o

core_archive.i: core_archive.c.i
.PHONY : core_archive.i

# target to preprocess a source file
core_archive.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arc.dir/build.make CMakeFiles/arc.dir/core_archive.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/core_archive.c.i
.PHONY : core_archive.c.i

core_archive.s: core_archive.c.s
.PHONY : core_archive.s

# target to generate assembly for a file
core_archive.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arc.dir/build.make CMakeFiles/arc.dir/core_archive.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/core_archive.c.s
.PHONY : core_archive.c.s

core_lua.o: core_lua.c.o
.PHONY : core_lua.o

# target to build an object file
core_lua.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/core_lua.c.o
.PHONY : core_lua.c.o

core_lua.i: core_lua.c.i
.PHONY : core_lua.i

# target to preprocess a source file
core_lua.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/core_lua.c.i
.PHONY : core_lua.c.i

core_lua.s: core_lua.c.s
.PHONY : core_lua.s

# target to generate assembly for a file
core_lua.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/core_lua.c.s
.PHONY : core_lua.c.s

core_lua_api.o: core_lua_api.c.o
.PHONY : core_lua_api.o

# target to build an object file
core_lua_api.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/core_lua_api.c.o
.PHONY : core_lua_api.c.o

core_lua_api.i: core_lua_api.c.i
.PHONY : core_lua_api.i

# target to preprocess a source file
core_lua_api.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/core_lua_api.c.i
.PHONY : core_lua_api.c.i

core_lua_api.s: core_lua_api.c.s
.PHONY : core_lua_api.s

# target to generate assembly for a file
core_lua_api.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/core_lua_api.c.s
.PHONY : core_lua_api.c.s

core_renderer.o: core_renderer.c.o
.PHONY : core_renderer.o

# target to build an object file
core_renderer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/core_renderer.c.o
.PHONY : core_renderer.c.o

core_renderer.i: core_renderer.c.i
.PHONY : core_renderer.i

# target to preprocess a source file
core_renderer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/core_renderer.c.i
.PHONY : core_renderer.c.i

core_renderer.s: core_renderer.c.s
.PHONY : core_renderer.s

# target to generate assembly for a file
core_renderer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/core_renderer.c.s
.PHONY : core_renderer.c.s

glad.o: glad.c.o
.PHONY : glad.o

# target to build an object file
glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/glad.c.o
.PHONY : glad.c.o

glad.i: glad.c.i
.PHONY : glad.i

# target to preprocess a source file
glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/glad.c.i
.PHONY : glad.c.i

glad.s: glad.c.s
.PHONY : glad.s

# target to generate assembly for a file
glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sausages.dir/build.make CMakeFiles/sausages.dir/glad.c.s
.PHONY : glad.c.s

tools/arc.o: tools/arc.c.o
.PHONY : tools/arc.o

# target to build an object file
tools/arc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arc.dir/build.make CMakeFiles/arc.dir/tools/arc.c.o
.PHONY : tools/arc.c.o

tools/arc.i: tools/arc.c.i
.PHONY : tools/arc.i

# target to preprocess a source file
tools/arc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arc.dir/build.make CMakeFiles/arc.dir/tools/arc.c.i
.PHONY : tools/arc.c.i

tools/arc.s: tools/arc.c.s
.PHONY : tools/arc.s

# target to generate assembly for a file
tools/arc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arc.dir/build.make CMakeFiles/arc.dir/tools/arc.c.s
.PHONY : tools/arc.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... shaders"
	@echo "... arc"
	@echo "... sausages"
	@echo "... core.o"
	@echo "... core.i"
	@echo "... core.s"
	@echo "... core_archive.o"
	@echo "... core_archive.i"
	@echo "... core_archive.s"
	@echo "... core_lua.o"
	@echo "... core_lua.i"
	@echo "... core_lua.s"
	@echo "... core_lua_api.o"
	@echo "... core_lua_api.i"
	@echo "... core_lua_api.s"
	@echo "... core_renderer.o"
	@echo "... core_renderer.i"
	@echo "... core_renderer.s"
	@echo "... glad.o"
	@echo "... glad.i"
	@echo "... glad.s"
	@echo "... tools/arc.o"
	@echo "... tools/arc.i"
	@echo "... tools/arc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

